sudo apt install lsd;
sudo apt install bat;
mkdir ~/descargas/firefox;
mkdir ~/.zsh;
cd ~/.zsh;
git clone https://github.com/zsh-users/zsh-autosuggestions;
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git;
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git;
cd ~;
rm ~/.zshrc; 
wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/.zshrc;
sudo ln -s -f ~/.zshrc /root/.zshrc;
mkdir ~/maquinas;
mkdir ~/.config/bin;
touch ~/.config/bin/name.txt;
touch ~/.config/bin/target.txt;
touch ~/.config/bin/ttl.txt;
touch ~/.config/bin/target_sys.txt;
cd /usr/share/i3blocks;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/usr/share/i3blocks/target_sys.sh;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/usr/share/i3blocks/target.sh;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/usr/share/i3blocks/hackthebox_status.sh;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/usr/share/i3blocks/ethernet_status.sh;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/usr/share/i3blocks/access_point.sh;
sudo chmod +x *;
mkdir ~/.config/kitty;
cd ~/.config/kitty;
sudo apt-get -y install kitty;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/kitty/color.ini;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/kitty/kitty.conf;
sudo cd ~/.config/i3;
sudo rm config;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/i3/i3blocks.conf;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/i3/config;
sudo wget https://raw.githubusercontent.com/KermitPurple96/i3-kitty/main/i3/clipboard_fix.sh;
sudo apt install xclip;
sudo chown -R root:root ~/.zsh;
sudo chown kermit:kermit /etc/hosts; 
sudo chmod -R 755 ~/.zsh;
sudo usermod --shell /usr/bin/zsh kermit;
sudo usermod --shell /usr/bin/zsh root;
cd /usr/local/share/fonts;
sudo wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip;
unzip Hack.zip;
rm Hack.zip;


