function tx
    echo "🖥️  TMUX Shortcuts (Alt prefix)"
    echo ""
    echo "📂 Windows (tabs):"
    echo "  Alt + ,     → Previous window"
    echo "  Alt + .     → Next window"
    echo "  Alt + n     → New window"
    echo "  Alt + w     → Close window"
    echo "  Alt + u     → Choose window tree"
    echo ""
    echo "🔲 Panes:"
    echo "  Alt + v     → Split vertically"
    echo "  Alt + h     → Split horizontally"
    echo "  Alt + c     → Close current pane"
    echo "  Alt + z     → Toggle zoom"
    echo ""
    echo "🧭 Navigation:"
    echo "  Alt + ←/→/↑/↓  → Move between panes"
    echo ""
    echo "📏 Resize panes:"
    echo "  Alt + Shift + K → Resize up"
    echo "  Alt + Shift + J → Resize down"
    echo "  Alt + Shift + H → Resize left"
    echo "  Alt + Shift + L → Resize right"
    echo ""
    echo "📋 Copy mode:"
    echo "  Alt + s     → Enter copy mode"
    echo "  Alt + a     → Start selection"
    echo "  Alt + y     → Copy to clipboard"
    echo "  Alt + q     → Exit copy mode"
    echo ""
    echo "🔄 Other:"
    echo "  Alt + Shift + S → New session"
    echo "  r           → Reload config"
    echo ""
    echo "🖱️  Mouse support is enabled"
end
